version: '2'

catalog:
  name: Sonarr
  version: 152-rancher1
  minimum_rancher_version: v0.59.0
  maintainer: Chris Seto
  uuid: sonarr-0

  questions:
    - variable: sonarr_version
      label: Sonarr Version
      description: The Sonarr version to run
      required: false
      type: enum
      default: latest
      options:
        - develop
        - latest
        - '152'
        - '151'
        - '150'

    - variable: timezone
      label: Timezone
      description: |
        Set the timezone inside the container. For example: Europe/London. The complete list can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      default: America/New_York
      required: false
      type: string

    - variable: tv_path
      label: TV Series Path
      description: location of TV library on disk
      default: ''
      required: true
      type: string

    - variable: config_path
      label: Config Path
      description: Database and Sonarr configs
      default: ''
      required: true
      type: string

    - variable: download_path
      label: Temporary Downloads Path
      description: 'TODO'
      default: ''
      required: false
      type: string

services:
  sonarr:
    scale: 1
    retain_ip: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8989
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
